CDM-RS: update usage of react-router-dom (move Router to MainApp, use withRouter HOC in App.js, Listent to location change), update EditorWithMarkedWordFeature.js (do nothing, if click on the cdmWordId is the same as strText, or in other word if emrWord is already changed), add IsShowCdmWordList state (show only if state.word.similarWords.data is Ok)
Note:
- Can not useLocation hook because of MainApp is not a functional component
Error: invalid hook call
- https://reactjs.org/warnings/invalid-hook-call-warning.html
- https://medium.com/@bryantjiminson/reactjs-how-to-handle-invalid-hook-call-warning-uncaught-error-invalid-hook-call-49ca32aa0d14
- https://github.com/ReactTraining/react-router/issues/7555

Refs:
- https://stackoverflow.com/questions/45373742/detect-route-change-with-react-router/45373907